// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd4pqgxyvzLYdvf9YkVXL7B_ISNahh2Cs',
    appId: '1:405022470668:web:5fd695b6ff87a2bf4d3429',
    messagingSenderId: '405022470668',
    projectId: 'flutter-demos-67589',
    authDomain: 'flutter-demos-67589.firebaseapp.com',
    storageBucket: 'flutter-demos-67589.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArKrR-UpzNdaIFWb8jKBLSkRgr4iM_9P0',
    appId: '1:405022470668:android:5b46cc9fc53f93714d3429',
    messagingSenderId: '405022470668',
    projectId: 'flutter-demos-67589',
    storageBucket: 'flutter-demos-67589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyfPhAga-ie8vDbNi0HwXiStX56BD9tLg',
    appId: '1:405022470668:ios:54bb7710c61d9b9a4d3429',
    messagingSenderId: '405022470668',
    projectId: 'flutter-demos-67589',
    storageBucket: 'flutter-demos-67589.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyfPhAga-ie8vDbNi0HwXiStX56BD9tLg',
    appId: '1:405022470668:ios:54bb7710c61d9b9a4d3429',
    messagingSenderId: '405022470668',
    projectId: 'flutter-demos-67589',
    storageBucket: 'flutter-demos-67589.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd4pqgxyvzLYdvf9YkVXL7B_ISNahh2Cs',
    appId: '1:405022470668:web:12dcb50480bc36824d3429',
    messagingSenderId: '405022470668',
    projectId: 'flutter-demos-67589',
    authDomain: 'flutter-demos-67589.firebaseapp.com',
    storageBucket: 'flutter-demos-67589.appspot.com',
  );
}
