// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJVgUA_lMT3-X1NqLigWRxwgS5pPKCK5o',
    appId: '1:74418340467:web:42c0012fe12c9d2aa3e006',
    messagingSenderId: '74418340467',
    projectId: 'fir-demos-8724b',
    authDomain: 'fir-demos-8724b.firebaseapp.com',
    storageBucket: 'fir-demos-8724b.appspot.com',
    measurementId: 'G-6L6ZZJGCLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlfWlxaAlB6WcpQoQ6N69zKREX8z3USmE',
    appId: '1:74418340467:android:2b9026d40589b62ea3e006',
    messagingSenderId: '74418340467',
    projectId: 'fir-demos-8724b',
    storageBucket: 'fir-demos-8724b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByd1eTa1KSm9zmTBkEBjyyhRsTLhwuqjg',
    appId: '1:74418340467:ios:5ad34de3bfd03605a3e006',
    messagingSenderId: '74418340467',
    projectId: 'fir-demos-8724b',
    storageBucket: 'fir-demos-8724b.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByd1eTa1KSm9zmTBkEBjyyhRsTLhwuqjg',
    appId: '1:74418340467:ios:5ad34de3bfd03605a3e006',
    messagingSenderId: '74418340467',
    projectId: 'fir-demos-8724b',
    storageBucket: 'fir-demos-8724b.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJVgUA_lMT3-X1NqLigWRxwgS5pPKCK5o',
    appId: '1:74418340467:web:fee496c2c7af018da3e006',
    messagingSenderId: '74418340467',
    projectId: 'fir-demos-8724b',
    authDomain: 'fir-demos-8724b.firebaseapp.com',
    storageBucket: 'fir-demos-8724b.appspot.com',
    measurementId: 'G-3ZGHE45JTV',
  );
}
