// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import '.env.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: apiKeyAndroid,
    appId: '1:863380056866:android:ef70042d76618e3275137b',
    messagingSenderId: '863380056866',
    projectId: 'crud-tutorial-469ed',
    storageBucket: 'crud-tutorial-469ed.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKeyIOS,
    appId: '1:863380056866:ios:128be2c775c0dbf475137b',
    messagingSenderId: '863380056866',
    projectId: 'crud-tutorial-469ed',
    storageBucket: 'crud-tutorial-469ed.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
